spring:
  application:
    name: metaphor-llm-processor

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
    retry:
      max-attempts: 10
      backoff:
        initial-interval: 2000 # 2 seconds
        multiplier: 5
        max-interval: 180000 # 3 minutes
      on-http-codes: 429, 502, 503

  data:
    mongodb:
      port: 27017
      host: localhost

metaphor:
  system-prompt: #TODO

indexing:
  max-retry: 3
  retry-interval-in-millis: 30000

